name: Documentation

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docs:
    name: Documentation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Windows Fonts
        run: |
          wget --output-document="Win11.zip" "https://github.com/liblaf/win-fonts/releases/download/Win11/Win11-Chinese_Simplified.zip"
          7z x -o"Win11" Win11.zip
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: writing/thuthesis-example.tex
          work_in_root_file_dir: true
          extra_fonts: Win11
          latexmk_use_xelatex: true
      - name: Copy PDF
        run: |
          install -D --mode="u=rw,go=r" --no-target-directory --verbose "writing/thuthesis-example.pdf" "dist/thesis.pdf"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
