name: Documentation

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Windows Fonts
        run: |
          wget --output-document="Win11.zip" "https://github.com/liblaf/win-fonts/releases/download/Win11/Win11-Chinese_Simplified.zip"
          7z x -o"Win11" Win11.zip
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: writing/thuthesis-example.tex
          work_in_root_file_dir: true
          extra_fonts: Win11
          latexmk_use_xelatex: true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: writing
          path: writing/thuthesis-example.pdf

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - docs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: writing
          path: writing
      - name: Create GitHub Release
        run: |
          gh release --repo="${{ github.repository }}" delete "writing" --cleanup-tag || true
          gh release --repo="${{ github.repository }}" create "writing" writing/thuthesis-example.pdf --latest --title="writing"
        env:
          GH_TOKEN: ${{ github.token }}
